apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello.fullname" . }}
  labels:
    {{- include "hello.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.prometheus.enabled }}
    prometheus.io/scrape: {{ .Values.prometheus.service.scrape | quote }}
    prometheus.io/path: {{ .Values.prometheus.service.path | quote }}
    prometheus.io/port: {{ .Values.prometheus.service.port | quote }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: 80
  - name: metrics
    port: {{ .Values.service.metricsPort }}
    targetPort: 9113
  selector:
    {{- include "hello.selectorLabels" . | nindent 4 }}